/* ============================================================
 * 热梗档案馆 · 数据文件
 * ------------------------------------------------------------
 * 所有数据都在这里维护，改完刷新页面即可。
 * videoUrl 使用 B 站搜索链接（永远有效），也可以换成具体视频 BV 链接。
 * animation 可选：textPop(文字弹跳) / dance(火柴人跳舞) / emojiRain(粒子雨)
 *              / shake(剧烈抖动) / fire(火焰) / flower(开花) / ring(光环)
 * ============================================================ */

/* ---------- 近10天最热梗（首页轮播 + 卡片墙） ---------- */
/* 数据抓取自 B 站官方热门/热搜接口，抓取时间：2026-08-01 */
const RECENT_MEMES = [
  {
    id: 'r13',
    name: '😨"后室里的乌鲁鲁"😰',
    emoji: '🎮',
    date: '2026-08-09',
    hot: 88,
    tags: ['B站热门', '今日'],
    desc: 'B站今日热门第13名：😨"后室里的乌鲁鲁"😰。',
    animation: 'flower',
    animText: '😨"后室里的乌鲁鲁"�…',
    emojis: ['🎮', '⚡'],
    color: '#ff9ff3',
    videoUrl: 'https://www.bilibili.com/video/BV1YYuN6tEWC',
    source: 'B站今日热门（实时抓取）'
  },
  {
    id: 'r24',
    name: '【独家】《凡人修仙传之慕兰之战》…',
    emoji: '🎵',
    date: '2026-08-09',
    hot: 77,
    tags: ['B站热门', '今日'],
    desc: 'B站今日热门第24名：【独家】《凡人修仙传之慕兰之战》第10集【总第186集】。',
    animation: 'emojiRain',
    animText: '独家《凡人修仙传之慕兰之…',
    emojis: ['🎵', '⚡'],
    color: '#5f27cd',
    videoUrl: 'https://www.bilibili.com/video/BV1uduP69Esr',
    source: 'B站今日热门（实时抓取）'
  },
  {
    id: 'r14',
    name: '[我的世界怪物学院] 逗逗小乐魂',
    emoji: '🎵',
    date: '2026-08-09',
    hot: 87,
    tags: ['B站热门', '今日'],
    desc: 'B站今日热门第14名：[我的世界怪物学院] 逗逗小乐魂。',
    animation: 'ring',
    animText: '我的世界怪物学院 逗逗小…',
    emojis: ['🎵', '⚡'],
    color: '#54a0ff',
    videoUrl: 'https://www.bilibili.com/video/BV1quug6JE11',
    source: 'B站今日热门（实时抓取）'
  },
  {
    id: 'r11',
    name: '妈妈，你不能单挑大棕熊，坐坦克打…',
    emoji: '🔥',
    date: '2026-08-09',
    hot: 90,
    tags: ['B站热门', '今日'],
    desc: 'B站今日热门第11名：妈妈，你不能单挑大棕熊，坐坦克打枪吧！？！。',
    animation: 'shake',
    animText: '妈妈，你不能单挑大棕熊…',
    emojis: ['🔥', '⚡'],
    color: '#48dbfb',
    videoUrl: 'https://www.bilibili.com/video/BV1mDuu6aEDF',
    source: 'B站今日热门（实时抓取）'
  },
  {
    id: 'r14',
    name: '怪兽中 出了一个奥特曼的卧底',
    emoji: '🎵',
    date: '2026-08-09',
    hot: 87,
    tags: ['B站热门', '今日'],
    desc: 'B站今日热门第14名：怪兽中 出了一个奥特曼的卧底。',
    animation: 'ring',
    animText: '怪兽中 出了一个奥特曼的…',
    emojis: ['🎵', '⚡'],
    color: '#54a0ff',
    videoUrl: 'https://www.bilibili.com/video/BV1gnub6REqy',
    source: 'B站今日热门（实时抓取）'
  },
  {
    id: 'r15',
    name: '王从天降',
    emoji: '📺',
    date: '2026-08-09',
    hot: 86,
    tags: ['B站热门', '今日'],
    desc: 'B站今日热门第15名：王从天降。',
    animation: 'textPop',
    animText: '王从天降',
    emojis: ['📺', '⚡'],
    color: '#f368e0',
    videoUrl: 'https://www.bilibili.com/video/BV1vtMy63E4G',
    source: 'B站今日热门（实时抓取）'
  },
  {
    id: 'r16',
    name: '发烧梗',
    emoji: '⚡',
    date: '2026-08-09',
    hot: 85,
    tags: ['B站热门', '今日'],
    desc: 'B站今日热门第16名：发烧梗。',
    animation: 'dance',
    animText: '发烧梗',
    emojis: ['⚡', '⚡'],
    color: '#5f27cd',
    videoUrl: 'https://www.bilibili.com/video/BV1Unub69EpX',
    source: 'B站今日热门（实时抓取）'
  },
  {
    id: 'r13',
    name: '在东方明珠玩100人躲猫猫！奖金…',
    emoji: '🎮',
    date: '2026-08-09',
    hot: 88,
    tags: ['B站热门', '今日'],
    desc: 'B站今日热门第13名：在东方明珠玩100人躲猫猫！奖金10万元。',
    animation: 'flower',
    animText: '在东方明珠玩100人躲猫猫…',
    emojis: ['🎮', '⚡'],
    color: '#ff9ff3',
    videoUrl: 'https://www.bilibili.com/video/BV1ocu46fE1z',
    source: 'B站今日热门（实时抓取）'
  },
  {
    id: 'r14',
    name: '调色别再只会拉饱和度啦',
    emoji: '🎵',
    date: '2026-08-09',
    hot: 87,
    tags: ['B站热门', '今日'],
    desc: 'B站今日热门第14名：调色别再只会拉饱和度啦。',
    animation: 'ring',
    animText: '调色别再只会拉饱和度啦',
    emojis: ['🎵', '⚡'],
    color: '#54a0ff',
    videoUrl: 'https://www.bilibili.com/video/BV1TgMZ6cEYd',
    source: 'B站今日热门（实时抓取）'
  },
  {
    id: 'r15',
    name: '在贵州按猪遇见羡慕的婚礼',
    emoji: '📺',
    date: '2026-08-09',
    hot: 86,
    tags: ['B站热门', '今日'],
    desc: 'B站今日热门第15名：在贵州按猪遇见羡慕的婚礼。',
    animation: 'textPop',
    animText: '在贵州按猪遇见羡慕的婚礼',
    emojis: ['📺', '⚡'],
    color: '#f368e0',
    videoUrl: 'https://www.bilibili.com/video/BV1Bbun6jEaJ',
    source: 'B站今日热门（实时抓取）'
  },
];

/* ---------- 全网出圈热梗（流传度广的梗 + 爆火的人，不只热搜榜） ---------- */
const VIRAL_MEMES = [
  {
    id: 'v1',
    name: '中国人能飞（揽佬）',
    emoji: '🚀',
    date: '2026-08-05',
    hot: 100,
    tags: ['全网出圈', '说唱神曲', '人物'],
    desc: '惠州说唱歌手揽佬（陈序垲）登上美国电台《On The Radar》freestyle，唱响"中国人能飞，黄皮肤才对，讲中文才飞，中国就是美"。7月28日《国防时报》用其做航天/战机视频BGM直接抬咖出圈，8月5日登微博热搜，B站二创动辄数百万播放。',
    animation: 'ring',
    animText: '中国人能飞',
    emojis: ['🚀', '✈️', '🇨🇳'],
    color: '#ff6b6b',
    videoUrl: 'https://search.bilibili.com/all?keyword=%E4%B8%AD%E5%9B%BD%E4%BA%BA%E8%83%BD%E9%A3%9E',
    source: '全网流传（人工收录）'
  },
  {
    id: 'v2',
    name: 'OMG你吓到我了（papi酱）',
    emoji: '🎤',
    date: '2026-07',
    hot: 97,
    tags: ['AI单曲', '二创刷屏', '人物'],
    desc: 'papi酱AI单曲副歌"OMG你吓到我了"魔性洗脑，与"中国人能飞"并称2026夏天两大互联网声音记忆，翻唱二创刷屏。',
    animation: 'textPop',
    animText: 'OMG你吓到我了',
    emojis: ['🎤', '😱'],
    color: '#feca57',
    videoUrl: 'https://search.bilibili.com/all?keyword=OMG%E4%BD%A0%E5%90%93%E5%88%B0%E6%88%91%E4%BA%86',
    source: '全网流传（人工收录）'
  },
  {
    id: 'v3',
    name: '大展鸿图（揽佬）',
    emoji: '🏮',
    date: '2025-07',
    hot: 95,
    tags: ['海外爆火', '说唱', '人物'],
    desc: '揽佬代表作，"别墅里面唱K，水池里面银龙鱼"魔性歌词+舞蹈在中国台湾与英语世界爆火，曾以月听众302万登顶Spotify华语歌手第一。',
    animation: 'dance',
    animText: '大展鸿图',
    emojis: ['🏮', '🐟'],
    color: '#ff9ff3',
    videoUrl: 'https://search.bilibili.com/all?keyword=%E6%8F%BD%E4%BD%AC%E5%A4%A7%E5%B1%95%E9%B8%BF%E5%9B%BE',
    source: '全网流传（人工收录）'
  },
  {
    id: 'v4',
    name: '《别接我，我改！》（中国消防）',
    emoji: '🚒',
    date: '2026-08-08',
    hot: 94,
    tags: ['官方整活', 'B站热门'],
    desc: '中国消防官方号魔性整活视频，835万播放，官方下场玩梗的天花板，又好笑又正能量。',
    animation: 'fire',
    animText: '别接我，我改！',
    emojis: ['🚒', '🔥'],
    color: '#ff6b6b',
    videoUrl: 'https://search.bilibili.com/all?keyword=%E5%88%AB%E6%8E%A5%E6%88%91%E6%88%91%E6%94%B9',
    source: 'B站热门（全网流传）'
  },
  {
    id: 'v5',
    name: '欢迎来到研究生的世界',
    emoji: '🎓',
    date: '2026-08-08',
    hot: 93,
    tags: ['爆款视频', 'B站热门'],
    desc: 'UP主豆豆豆豆逗是我的整活视频，841万播放，研究生日常被演活了，全网研究生共鸣爆棚。',
    animation: 'textPop',
    animText: '欢迎来到研究生的世界',
    emojis: ['🎓', '📚'],
    color: '#54a0ff',
    videoUrl: 'https://search.bilibili.com/all?keyword=%E6%AC%A2%E8%BF%8E%E6%9D%A5%E5%88%B0%E7%A0%94%E7%A9%B6%E7%94%9F%E7%9A%84%E4%B8%96%E7%95%8C',
    source: 'B站热门（全网流传）'
  },
  {
    id: 'v6',
    name: '当和你一起玩的那个兄弟延迟过高',
    emoji: '🎮',
    date: '2026-08-08',
    hot: 92,
    tags: ['游戏整活', 'B站热门'],
    desc: '联机游戏延迟名场面，631万播放，"兄弟延迟过高"让每个开黑玩家都狠狠共情。',
    animation: 'shake',
    animText: '兄弟延迟过高',
    emojis: ['🎮', '⚡'],
    color: '#5f27cd',
    videoUrl: 'https://search.bilibili.com/all?keyword=%E5%BD%93%E5%92%8C%E4%BD%A0%E4%B8%80%E8%B5%B7%E7%8E%A9%E7%9A%84%E9%82%A3%E4%B8%AA%E5%85%84%E5%BC%9F%E5%BB%B6%E8%BF%9F%E8%BF%87%E9%AB%98',
    source: 'B站热门（全网流传）'
  },
  {
    id: 'v7',
    name: '见手青小炒火焰魔法',
    emoji: '🍄',
    date: '2026-08-08',
    hot: 90,
    tags: ['美食爆款', 'B站热门'],
    desc: '盗月社见手青小炒，云南厨师火焰魔法346万播放，又怕又馋，评论区全是"吃了见小人"的梗。',
    animation: 'fire',
    animText: '见手青火焰魔法',
    emojis: ['🍄', '🔥'],
    color: '#ff9ff3',
    videoUrl: 'https://search.bilibili.com/all?keyword=%E8%A7%81%E6%89%8B%E9%9D%92%E5%B0%8F%E7%82%92',
    source: 'B站热门（全网流传）'
  },
  {
    id: 'v8',
    name: '不要做挑战第二十一期',
    emoji: '🎯',
    date: '2026-08-08',
    hot: 89,
    tags: ['综艺整活', 'B站热门'],
    desc: '小潮院长"不要做挑战"系列第21期，216万播放，老牌整活IP持续长红，新一期照样上热门。',
    animation: 'shake',
    animText: '不要做挑战',
    emojis: ['🎯', '😤'],
    color: '#f368e0',
    videoUrl: 'https://search.bilibili.com/all?keyword=%E4%B8%8D%E8%A6%81%E5%81%9A%E6%8C%91%E6%88%98%E5%B0%8F%E6%BD%AE%E9%99%A2%E9%95%BF',
    source: 'B站热门（全网流传）'
  }
];

/* ---------- 今日热搜词（顶部滚动条） ---------- */
const HOT_WORDS = [
  'KSG战胜AG.AL赛后数据', '欢迎来龙餐馆是反战片吗', '台风白海豚', '堂主年马计划一周年', '歌剧老师锐评歌王之战', '曝费兰托雷斯和巴黎达成协议', '罗子君近期为何再次翻红', '曼联1-1巴黎', '当年的CF老玩家现在在做什么', '台风红色预警发布', 'WBG LNG', 'AG.AL KSG'
];

/* ---------- 近五年经典梗编年史 (2021-2026) ---------- */
const YEARS = [
  {
    year: '2021',
    title: '梗元年 · 万物皆可玩',
    color: '#ff8a65',
    memes: [
      { name: '芭比Q了', emoji: '🔥', animation: 'mcTnt', hot: 99,
        desc: '“完了，芭比Q了！”博主@达芬奇账号 的口头禅，意为“完蛋了”，红遍全网。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E8%8F%AD%E6%AF%94Q%E4%BA%86' },
      { name: '退！退！退！', emoji: '🧹', animation: 'shake', hot: 97,
        desc: '大妈用“击剑式”动作驱逐商贩的名场面，“退退退”成为万能驱邪咒语。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E9%80%80%E9%80%80%E9%80%80' },
      { name: '拿来吧你', emoji: '🫴', animation: 'textPop', hot: 95,
        desc: '“拿来吧你！”——理直气壮索要一切的万能句式，配合魔性表情包传播。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E6%8B%BF%E6%9D%A5%E5%90%A7%E4%BD%A0' },
      { name: '栓Q', emoji: '🙏', animation: 'textPop', hot: 94,
        desc: '“我真的会谢（栓Q）”英语 Thank you 的空耳，成为年度礼貌用语。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E6%A0%93Q' },
      { name: 'YYDS', emoji: '👑', animation: 'ring', hot: 93,
        desc: '“永远的神”拼音缩写，从电竞圈杀入日常，万物皆可 YYDS。',
        videoUrl: 'https://search.bilibili.com/all?keyword=YYDS' },
      { name: '你干嘛～哎哟', emoji: '😜', animation: 'shake', hot: 91,
        desc: '徐某坤“你干嘛～哎哟”魔性视频，油腻中带着喜感，被全网模仿。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E4%BD%A0%E5%B9%B2%E5%98%9B%E5%93%8E%E5%93%9F' },
      { name: '夺笋啊', emoji: '🎋', animation: 'emojiRain', hot: 89, emojis: ['🎋','😏','🐼'],
        desc: '“夺笋啊”=“多损啊”的谐音，形容人损到家了，配合大熊猫表情包食用。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E5%A4%BA%E7%AC%8B%E5%95%8A' },
      { name: '绝绝子', emoji: '✨', animation: 'emojiRain', hot: 87, emojis: ['✨','🌟','💫'],
        desc: '“绝了”的加强版，夸人夸到词穷时的终极形容词。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E7%BB%9D%E7%BB%9D%E5%AD%90' }
    ]
  },
  {
    year: '2022',
    title: '全民健身 · 羊了个羊',
    color: '#ffca28',
    memes: [
      { name: '刘畊宏女孩', emoji: '💃', animation: 'dance', hot: 99,
        desc: '“本草纲目”毽子操火遍全网，全网女孩化身刘畊宏女孩，跟着直播跳操。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E5%88%98%E7%95%8A%E5%AE%8F%E5%A5%B3%E5%AD%A9' },
      { name: '羊了个羊', emoji: '🐑', animation: 'emojiRain', hot: 98, emojis: ['🐑','🧩','😤'],
        desc: '第二关永远过不去的消除小游戏，全民上头，越菜越爱玩。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E7%BE%8A%E4%BA%86%E4%B8%AA%E7%BE%8A' },
      { name: '我是云南的', emoji: '💃', animation: 'dance', hot: 96,
        desc: '“我是云南的，云南怒江的……”魔性旋律搭配民族服饰，全网掀起家乡介绍热潮。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E6%88%91%E6%98%AF%E4%BA%91%E5%8D%97%E7%9A%84' },
      { name: '疯狂星期四', emoji: '🍗', animation: 'mcRain', hot: 95, emojis: ['🍗','💸','😭'],
        desc: '“今天是肯德基疯狂星期四，V我50！”——每周四准时刷屏的求打赏文学。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E7%96%AF%E7%8B%82%E6%98%9F%E6%9C%9F%E5%9B%9B' },
      { name: '听我说谢谢你', emoji: '🎵', animation: 'flower', hot: 93,
        desc: '感恩神曲被用滥后成为“精神污染”，从感动到折磨只差一个幼儿园表演。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E5%90%AC%E6%88%91%E8%AF%B4%E8%B0%A2%E8%B0%A2%E4%BD%A0' },
      { name: '孤勇者', emoji: '🎤', animation: 'fire', hot: 92,
        desc: '《孤勇者》小学生对暗号神曲，“爱你孤身走暗巷”一开口就是自己人。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E5%AD%A4%E5%8B%87%E8%80%85' },
      { name: '可达鸭', emoji: '🦆', animation: 'emojiRain', hot: 90, emojis: ['🦆','💃','🎵'],
        desc: '肯德基儿童套餐可达鸭玩具，魔性摆手舞蹈，二手价炒上天。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E5%8F%AF%E8%BE%BE%E9%B8%AD' },
      { name: '你礼貌吗', emoji: '🙄', animation: 'shake', hot: 88,
        desc: '面对冒犯行为的灵魂拷问：“你礼貌吗？”搭配翻白眼表情包。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E4%BD%A0%E7%A4%BC%E8%B2%8C%E5%90%97' }
    ]
  },
  {
    year: '2023',
    title: '科目三 · 挖呀挖',
    color: '#aed581',
    memes: [
      { name: '科目三', emoji: '🕺', animation: 'dance', hot: 100,
        desc: '广西“科目三”舞蹈：丝滑的摇花手+扭腰摆胯，从婚庆现场跳到世界舞台。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E7%A7%91%E7%9B%AE%E4%B8%89%E8%88%9E%E8%B9%88' },
      { name: '挖呀挖呀挖', emoji: '🌷', animation: 'flower', hot: 99,
        desc: '“在小小的花园里面挖呀挖呀挖”，幼师儿歌全网翻唱，成年人集体返老还童。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E6%8C%96%E5%91%80%E6%8C%96%E5%91%80%E6%8C%96' },
      { name: '显眼包', emoji: '🌟', animation: 'ring', hot: 98,
        desc: '指人群中爱出风头、自带笑点的人，“每个班都有一个显眼包”。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E6%98%BE%E7%9C%BC%E5%8C%85' },
      { name: '泰裤辣', emoji: '🕶️', animation: 'textPop', hot: 97,
        desc: '“太酷啦”的魔性口音版，来源于某歌手现场发言，配墨镜表情包食用更佳。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E6%B3%B0%E8%A3%A4%E8%BE%A3' },
      { name: '恐龙扛狼', emoji: '🦖', animation: 'shake', hot: 96,
        desc: '“恐龙扛狼扛狼扛”魔性空耳，源自云南山歌，配上霸王龙摇头表情包。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E6%81%90%E9%BE%99%E6%8A%97%E7%8B%BC' },
      { name: '遥遥领先', emoji: '🚀', animation: 'ring', hot: 95,
        desc: '华为发布会金句，被网友玩成“遥遥领先”四字真言，科技圈通用梗。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E9%81%A5%E9%81%A5%E9%A2%86%E5%85%88' },
      { name: '多巴胺穿搭', emoji: '🌈', animation: 'emojiRain', hot: 93, emojis: ['🌈','🎨','💃'],
        desc: '色彩鲜艳的穿搭风潮，“多巴胺女孩/男孩”占领夏天的街头和屏幕。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E5%A4%9A%E5%B7%B4%E8%83%BA%E7%A9%BF%E6%90%AD' },
      { name: 'i人e人', emoji: '🧊', animation: 'textPop', hot: 91,
        desc: 'MBTI 人格测试爆火，“i人（内向）/e人（外向）”成为社交自我介绍第一句。',
        videoUrl: 'https://search.bilibili.com/all?keyword=i%E4%BA%BAe%E4%BA%BA' },
      { name: '泼天的富贵', emoji: '💰', animation: 'emojiRain', hot: 90, emojis: ['💰','🤑','✨'],
        desc: '“这泼天的富贵终于轮到我了！”形容好运突然降临，常用于品牌翻红现场。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E6%B3%BC%E5%A4%A9%E7%9A%84%E5%AF%8C%E8%B4%B5' },
      { name: '尊嘟假嘟', emoji: '🐹', animation: 'textPop', hot: 89,
        desc: '“真的假的”的卖萌口音版，配合小仓鼠表情包，“尊嘟假嘟O.o”席卷评论区。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E5%B0%8A%E5%98%9F%E5%81%87%E5%98%9F' }
    ]
  },
  {
    year: '2024',
    title: '南北互宠 · 抽象元年',
    color: '#4fc3f7',
    memes: [
      { name: '南方小土豆', emoji: '🥔', animation: 'textPop', hot: 99,
        desc: '哈尔滨文旅爆火，南方游客被东北人宠成“小土豆”，南北互宠名场面。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E5%8D%97%E6%96%B9%E5%B0%8F%E5%9C%9F%E8%B1%86' },
      { name: 'City不City', emoji: '🏙️', animation: 'ring', hot: 98,
        desc: '外国博主“保保熊”的中英混搭：“City不City啊？”——洋气不洋气？',
        videoUrl: 'https://search.bilibili.com/all?keyword=City%E4%B8%8DCity' },
      { name: '硬控', emoji: '🎯', animation: 'shake', hot: 97,
        desc: '“被XX硬控30秒”——被某个视频/画面牢牢定住，动弹不得。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E7%A1%AC%E6%8E%A7' },
      { name: '搞抽象', emoji: '🎭', animation: 'textPop', hot: 96,
        desc: '“抽象”文化登峰造极，“搞抽象”成为年轻人最高级的赞美与调侃。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E6%90%9E%E6%8A%BD%E8%B1%A1' },
      { name: '班味', emoji: '😮‍💨', animation: 'emojiRain', hot: 95, emojis: ['😮‍💨','💼','☕'],
        desc: '打工人的疲惫感溢出屏幕，“班味太重了”成为职场人互相确认的眼神。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E7%8F%AD%E5%91%B3' },
      { name: '小孩哥/小孩姐', emoji: '🧒', animation: 'textPop', hot: 94,
        desc: '对能力超强小朋友的最高称呼，“小孩哥出手就是降维打击”。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E5%B0%8F%E5%AD%A9%E5%93%A5' },
      { name: '黑神话·悟空', emoji: '🐒', animation: 'fire', hot: 93,
        desc: '国产3A游戏《黑神话：悟空》发售，“天命人”集结，村里第一个大学生。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E9%BB%91%E7%A5%9E%E8%AF%9D%E6%82%9F%E7%A9%BA' },
      { name: '吗喽', emoji: '🐒', animation: 'emojiRain', hot: 92, emojis: ['🐒','😮‍💨','🍌'],
        desc: '“吗喽的命也是命”——打工人自嘲为“吗喽”（猴子），配上猴子表情包。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E5%90%97%E5%96%BD' },
      { name: '包赢/包你满意', emoji: '🤝', animation: 'textPop', hot: 91,
        desc: '“包”=“保证”，来自某主播口癖，“包赢”“包你满意”成了承诺万能句式。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E5%8C%85%E4%BD%A0%E6%BB%A1%E6%84%8F' },
      { name: '松弛感', emoji: '🛋️', animation: 'flower', hot: 90,
        desc: '“松弛感”成为年度生活理想：不紧绷、不内耗，主打一个随遇而安。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E6%9D%BE%E5%BC%9B%E6%84%9F' }
    ]
  },
  {
    year: '2025',
    title: 'AI浪潮 · 抽象升级',
    color: '#ba68c8',
    memes: [
      { name: '哪吒2 · 我命由我不由天', emoji: '🔥', animation: 'fire', hot: 100,
        desc: '《哪吒之魔童闹海》登顶影史票房冠军，“我命由我不由天”再度响彻全网。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E5%93%AA%E5%90%922' },
      { name: 'DeepSeek', emoji: '🤖', animation: 'textPop', hot: 99,
        desc: '国产大模型 DeepSeek 全球爆火，“下载DeepSeek了吗”成了新年问候语。',
        videoUrl: 'https://search.bilibili.com/all?keyword=DeepSeek' },
      { name: 'Passion！', emoji: '🔥', animation: 'fire', hot: 98,
        desc: '脱口秀演员付航夺冠名场面：“Passion！”——用热爱点燃全场。',
        videoUrl: 'https://search.bilibili.com/all?keyword=Passion%E4%BB%98%E8%88%AA' },
      { name: '甲亢哥', emoji: '😆', animation: 'shake', hot: 97,
        desc: '外国顶流“甲亢哥”中国行直播，夸张反应+中国体验成全球流量密码。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E7%94%B2%E4%BA%A2%E5%93%A5' },
      { name: '天塌了', emoji: '🌋', animation: 'shake', hot: 96,
        desc: '“天塌了！”——遇到离谱事情的夸张反应，搭配倒塌大楼表情包。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E5%A4%A9%E5%A1%8C%E4%BA%86' },
      { name: '吃谷', emoji: '🍙', animation: 'emojiRain', hot: 95, emojis: ['🍙','🛍️','💖'],
        desc: '“吃谷”=买周边（goods），二次元经济全面爆发，吃谷人吃谷魂。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E5%90%83%E8%B0%B7' },
      { name: '爆改', emoji: '🔧', animation: 'ring', hot: 94,
        desc: '“爆改”万物：改造出租屋、改造自己，从土到潮只需一个爆改。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E7%88%86%E6%94%B9' },
      { name: '杭州六小龙', emoji: '🐉', animation: 'ring', hot: 93,
        desc: '以深度求索为首的杭州科技“六小龙”出圈，中国AI叙事的新名片。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E6%9D%AD%E5%B7%9E%E5%85%AD%E5%B0%8F%E9%BE%99' }
    ]
  },
  {
    year: '2026',
    title: '进行时 · 每周都在换',
    color: '#f06292',
    memes: [
      { name: '谁能抵挡迪迦的魅力', emoji: '🦸', animation: 'ring', hot: 98,
        desc: '迪迦经典台词翻红，“谁能抵挡迪迦的魅力”变身挑战刷屏。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E8%B0%81%E8%83%BD%E6%8A%B5%E6%8C%A1%E8%BF%AA%E8%BF%A6%E7%9A%84%E9%AD%85%E5%8A%9B' },
      { name: '大周礼时代', emoji: '🏛️', animation: 'textPop', hot: 95,
        desc: '古代礼制为背景的整活短剧系列，全网二创停不下来。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E5%A4%A7%E5%91%A8%E7%A4%BC%E6%97%B6%E4%BB%A3' },
      { name: '实测DeepSeek V4 Flash', emoji: '🤖', animation: 'textPop', hot: 92,
        desc: 'DeepSeek V4 Flash 实测整活风潮，“实测XX”成为新流量密码。',
        videoUrl: 'https://search.bilibili.com/all?keyword=DeepSeek%20V4' },
      { name: '外军想回家，解放军回复fight', emoji: '🪖', animation: 'shake', hot: 90,
        desc: '军演对峙名场面表情包化，“fight”梗火出圈。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E5%A4%96%E5%86%9B%E6%83%B3%E5%9B%9E%E5%AE%B6' },
      { name: '颠沛流离文学', emoji: '🌧️', animation: 'emojiRain', hot: 88, emojis: ['🌧️','💔','🌙'],
        desc: '“什么样的结局才配得上这一路的颠沛流离”——年度emo文案。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E9%A2%A0%E6%B2%9B%E6%B5%81%E7%A6%BB' },
      { name: '建军99周年致敬', emoji: '🎖️', animation: 'fire', hot: 86,
        desc: '八一建军节全网致敬，“清澈的爱只为中国”再度刷屏。',
        videoUrl: 'https://search.bilibili.com/all?keyword=%E5%BB%BA%E5%86%9B99%E5%91%A8%E5%B9%B4' }
    ]
  }
];
